### ISSUE TITLE
libtsm fails to build with musl libc on Alpine Linux

### ISSUE THREAD

**Issue by plntyk** [Aetf/libtsm#12]
this trivial patch

```
diff --git a/external/wcwidth/wcwidth.h b/external/wcwidth/wcwidth.h
index 38c17ac..bb98ab0 100644
--- a/external/wcwidth/wcwidth.h
+++ b/external/wcwidth/wcwidth.h
@@ -3,10 +3,14 @@
 
 #include <stdlib.h>
 
-__BEGIN_DECLS
+#ifdef __cplusplus
+extern "C" {
+#endif
 
 int wcwidth(wchar_t ucs);
 
-__END_DECLS
+#ifdef __cplusplus
+}
+#endif
 
 #endif

```

fixes the issue, see https://wiki.musl-libc.org/faq.html

**Comment by Aetf** [comment]
Thanks for the report! Could you please test the develop branch which contains the fix before I merge to master and close this?

**Comment by plntyk** [comment]
compilation of develop branch of libtsm works
Freshly compiled kmscon works with that libtsm on Alpine Linux with musl-libc.
