### ISSUE TITLE
Folder names in releases not in PV form

### ISSUE THREAD

**Issue by mgomersbach** [Aetf/libtsm#14]
In Gentoo portage for example the build/package system expects the source to usually be in the form of "Packagename-Version.tar.gz"
Although I could work around with some variables in ebuild script system.
But would it be possible for the releases to have PV form again like the original?

**Comment by Aetf** [comment]
I'm still using the same tagging name (`libtsm-4.0.0`) as before (`libtsm-3`). The only difference is now it also includes minor and patch numbers.

Did it work before? And how did you download the release file?

**Comment by Aetf** [comment]
Okay, I see. GitHub automatically prepends repo name to the tag name in the downloaded tarball. Probably I should change tag name as `v4.0.0` which is more common on GitHub.

**Comment by Aetf** [comment]
I'll do a proper `v4.0.0` release (or probably `v4.0.1`?) in a few days after finishing the working porting the build system to cmake.

**Comment by Aetf** [comment]
Done release `v4.0.1`. I'm closing this for now. Please reopen if there are still problems.
