### ISSUE TITLE
Setting custom color palettes.

### ISSUE THREAD

**Issue by timmypidashev** [Aetf/libtsm#19]
Hello, first off thank you for a maintained fork of libtsm. I am trying to get a gruvbox-like theme working, and I'm having trouble figuring out how it works. After failing to properly install the dependency from the defunct libtsm, I found this fork. In the readme, you mention support for custom palettes via an api. Am i correct to assume that the custom palette would have to be defined by hand in the code itself(tsm-vte.c)? And if so, how would I go about doing so once the lib is installed on my system. Or am I wrong and it can be define in the (kmscon.conf) file? I am fairly new to c, so my apologies in advance if I botched up this question already. Thanks in advance!

**Comment by timmypidashev** [comment]
Ok nevermind I just forked this repo and modified the PKGBUILD at install

**Comment by Aetf** [comment]
Glad that at least you figured out a way to get a palette working for you.

I implemented the custom palette support in libtsm (`tsm_vte_set_custom_palette`) a while ago, but I never got the time to actually wire it up in kmscon. So yeah currently there's no way to use it for kmscon other than modifying the code.

**Comment by timmypidashev** [comment]
Gotchu, that's all good. Very happy there is a maintained tsm fork altogether!
