### ISSUE TITLE
DECRQM resets terminal

### ISSUE THREAD

**Issue by aheck** [Aetf/libtsm#26]
When I start vim on macOS 12.3.1 on an M1 Mac in a terminal based on libtsm I get the strange behaviour that the terminal switches to alternate screen but the content of the screen doesn't look like vim but exactly like the content of the main screen before starting vim. Only difference is that the cursor is in the top left. Only when I enter the usual vim commands parts of the status line appear and it becomes clear that vim is actually running. It is just that the terminal went back to operating on the main screen.

That problem doesn't happen on my Intel Mac with macOS 10.15 and neither does it happen on Linux.

Further investigation showed that at after sending the sequences for its usual startup screen vim sends the sequence \u001B[?12$p. (I have a full record of all the sequences sent by vim leading to the problem but it is a bit lengthy so I omit it here)

When I fed libtsm with the data I captured from vim and used a delay to make it happen in slow motion I could clearly see that vim actually appears on screen at first and it is only with the last line of input that the screen is messed up.

The sequence in question is handled in tsm-vte.c at this location:

1775		} else if (vte->csi_flags & CSI_CASH) {
1776			/* DECRQM: Request DEC Private Mode */
1777			/* If CSI_WHAT is set, then enable,
1778			 * otherwise disable */
1779			csi_soft_reset(vte);
1780		} else {

If I comment out the soft reset in line 1779 the problem is gone and vim appears on screen in all its glory.

AFAIK this DECRQM is used by the client to request some information. Therefore doing a soft reset seems like a bad way of handling it even if it is not implemented, yet.

PS: When I feed libtsm on other platforms with this sequence the screen is messed up in the same way. It is just that vim on other platforms doesn't send this sequence in the first place (no idea why it does it on the M1 Mac).

**Comment by Aetf** [comment]
That line does look suspicious. Could you do a PR to remove that with a small unit test, given you already got captured vim data? Thanks!

Also, I want to make sure not responding is the correct way to do it. Do you have any insights about how vim handles this when the line is commented out?

**Comment by aheck** [comment]
I wrote a minimal unit test that sets the terminal to alternate screen mode, sends the "dangerous" control sequence and checks if the screen is still in alternate mode (which it is not if a reset happened).

The better way to ignoring the request would be to implement it. But for the moment I don't understand this feature well enough to do it myself.

This page gives a good overview: https://vt100.net/docs/vt510-rm/DECRQM.html

The xterm control sequence documentation (https://invisible-island.net/xterm/ctlseqs/ctlseqs.html) also has some info:

<quote>
CSI Ps $ p
          Request ANSI mode (DECRQM).  For VT300 and up, reply DECRPM is
            CSI Ps; Pm $ y
          where Ps is the mode number as in SM/RM, and Pm is the mode
          value:
            0 - not recognized
            1 - set
            2 - reset
            3 - permanently set
            4 - permanently reset

CSI ? Ps $ p
          Request DEC private mode (DECRQM).  For VT300 and up, reply
          DECRPM is
            CSI ? Ps; Pm $ y
          where Ps is the mode number as in DECSET/DECSET, Pm is the
          mode value as in the ANSI DECRQM.
          Two private modes are read-only (i.e., 1 3  and 1 4 ),
          provided only for reporting their values using this control
          sequence.  They correspond to the resources cursorBlink and
          cursorBlinkXOR.
</quote>

The code 12 used in this request stands for Send/Receive Mode (SRM). xterm answers this request with \033[?12;2$y straight after startup.

Vim worked perfectly fine when ignoring the DECRQM control sequence. I didn't dig deeper to find out where this control sequence originates from, though.

For the moment I think it is best to just ignore the request until somebody volunteers to implement it. At least it seems to be much better than to reset the terminal violently. Probably the only good use case for this "implementation" was to remember the developers that something still needs to be implemented.
